[buildPlans.pyrasevid]
family = "pyrasevid"
spacing = "normal"
serifs = "sans"
no-cv-ss = false
 
[buildPlans.pyrasevid.variants.design]
capital-a = "curly-serifless"
capital-b = "standard-unilateral-serifed"
capital-c = "bilateral-inward-serifed"
capital-d = "more-rounded-unilateral-serifed"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothless-corner-serifless-hooked"
capital-h = "top-left-serifed"
capital-i = "serifed"
capital-j = "flat-hook-serifed"
capital-k = "curly-serifless"
capital-l = "serifless"
capital-m = "hanging-motion-serifed"
capital-p = "open"
capital-q = "horizontal-tailed"
capital-r = "curly-open"
capital-s = "unilateral-inward-serifed"
capital-u = "toothless-corner"
capital-v = "curly"
capital-w = "curly"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "curly-serifless"
a = "single-storey-earless-corner-tailed"
b = "toothless-corner"
c = "unilateral-inward-serifed"
d = "toothless-corner-serifless"
e = "flat-crossbar"
f = "serifless"
g = "single-storey-earless-corner-flat-hook"
h = "straight"
i = "serifed-flat-tailed"
j = "flat-hook-serifed"
k = "curly-serifless"
l = "serifed-flat-tailed"
m = "earless-corner-double-arch-short-leg"
n = "earless-corner-straight"
p = "earless-corner"
q = "earless-corner-tailed"
r = "serifless"
s = "unilateral-inward-serifed"
t = "flat-hook-short-neck2"
u = "toothless-corner"
v = "curly"
w = "curly"
x = "curly-serifless"
y = "curly-turn"
z = "curly-serifless"
long-s = "flat-hook"
eszet = "longs-s-lig"
turn-v = "curly"
lower-alpha = "crossing"
lower-delta = "rounded"
capital-gamma = "serifless"
zero = "slashed"
one = "no-base-long-top-serif"
two = "curly-neck"
three = "two-arcs"
four = "semi-open"
five = "vertical-upper-left-bar"
six = "closed-contour"
seven = "bend-crossbar"
eight = "crossing-asymmetric"
nine = "closed-contour"
asterisk = "penta-low"
caret = "low"
paren = "large-contour"
brace = "curly-flat-boundary"
ampersand = "et-toothless-rounded"
at = "short"
dollar = "interrupted-cap"
cent = "bar-interrupted"
percent = "rings-segmented-slash"
lig-ltgteq = "slanted"
question = "corner-flat-hooked"
punctuation-dot = "square"
 
[buildPlans.pyrasevid.variants.italic]
capital-a = "curly-top-serifed"
capital-b = "standard-bilateral-serifed"
capital-c = "unilateral-inward-serifed"
capital-d = "standard-bilateral-serifed"
capital-e = "top-left-serifed"
capital-f = "top-left-serifed"
capital-g = "toothed-inward-serifed-hooked"
capital-h = "top-left-bottom-right-serifed"
capital-i = "serifed"
capital-j = "flat-hook-serifed-both-sides"
capital-l = "motion-serifed"
capital-n = "motion-serifed"
capital-p = "open-motion-serifed"
capital-r = "curly-open-motion-serifed"
capital-s = "bilateral-inward-serifed"
capital-t = "motion-serifed"
capital-u = "toothless-corner-unilateral-motion-serifed"
capital-v = "curly-motion-serifed"
capital-w = "curly-motion-serifed"
capital-x = "curly-motion-serifed"
capital-y = "curly-motion-serifed"
capital-z = "curly-bottom-serifed-with-crossbar"
a = "single-storey-earless-corner-serifed"
b = "toothless-corner-motion-serifed"
c = "bilateral-inward-serifed"
d = "toothless-corner-serifed"
e = "rounded"
g = "single-storey-flat-hook-serifed"
h = "straight-motion-serifed"
i = "serifed-diagonal-tailed"
j = "diagonal-tailed-serifed"
k = "cursive-top-left-serifed"
l = "serifed-diagonal-tailed"
m = "short-leg-tailed-top-left-serifed"
n = "tailed-motion-serifed"
p = "motion-serifed"
q = "earless-corner-diagonal-tailed"
r = "top-serifed"
s = "bilateral-inward-serifed"
t = "diagonal-tailed-short-neck2"
u = "toothless-corner-motion-serifed"
v = "cursive-serifed"
w = "curly-motion-serifed"
x = "curly-motion-serifed"
y = "curly-turn-motion-serifed"
z = "curly-serifed"
seven = "bend-crossbar-serifed"
 
  [buildPlans.pyrasevid.ligations]
  inherits = "dlig"

[buildPlans.pyrasevid-term]
family = "pyrasevid term"
spacing = "term"
serifs = "sans"
no-cv-ss = false
 
[buildPlans.pyrasevid-term.variants.design]
capital-a = "curly-serifless"
capital-b = "standard-unilateral-serifed"
capital-c = "bilateral-inward-serifed"
capital-d = "more-rounded-unilateral-serifed"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothless-corner-serifless-hooked"
capital-h = "top-left-serifed"
capital-i = "serifed"
capital-j = "flat-hook-serifed"
capital-k = "curly-serifless"
capital-l = "serifless"
capital-m = "hanging-motion-serifed"
capital-p = "open"
capital-q = "horizontal-tailed"
capital-r = "curly-open"
capital-s = "unilateral-inward-serifed"
capital-u = "toothless-corner"
capital-v = "curly"
capital-w = "curly"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "curly-serifless"
a = "single-storey-earless-corner-tailed"
b = "toothless-corner"
c = "unilateral-inward-serifed"
d = "toothless-corner-serifless"
e = "flat-crossbar"
f = "serifless"
g = "single-storey-earless-corner-flat-hook"
h = "straight"
i = "serifed-flat-tailed"
j = "flat-hook-serifed"
k = "curly-serifless"
l = "serifed-flat-tailed"
m = "earless-corner-double-arch-short-leg"
n = "earless-corner-straight"
p = "earless-corner"
q = "earless-corner-tailed"
r = "serifless"
s = "unilateral-inward-serifed"
t = "flat-hook-short-neck2"
u = "toothless-corner"
v = "curly"
w = "curly"
x = "curly-serifless"
y = "curly-turn"
z = "curly-serifless"
long-s = "flat-hook"
eszet = "longs-s-lig"
turn-v = "curly"
lower-alpha = "crossing"
lower-delta = "rounded"
capital-gamma = "serifless"
zero = "slashed"
one = "no-base-long-top-serif"
two = "curly-neck"
three = "two-arcs"
four = "semi-open"
five = "vertical-upper-left-bar"
six = "closed-contour"
seven = "bend-crossbar"
eight = "crossing-asymmetric"
nine = "closed-contour"
asterisk = "penta-low"
caret = "low"
paren = "large-contour"
brace = "curly-flat-boundary"
ampersand = "et-toothless-rounded"
at = "short"
dollar = "interrupted-cap"
cent = "bar-interrupted"
percent = "rings-segmented-slash"
lig-ltgteq = "slanted"
question = "corner-flat-hooked"
punctuation-dot = "square"
 
[buildPlans.pyrasevid-term.variants.italic]
capital-a = "curly-top-serifed"
capital-b = "standard-bilateral-serifed"
capital-c = "unilateral-inward-serifed"
capital-d = "standard-bilateral-serifed"
capital-e = "top-left-serifed"
capital-f = "top-left-serifed"
capital-g = "toothed-inward-serifed-hooked"
capital-h = "top-left-bottom-right-serifed"
capital-i = "serifed"
capital-j = "flat-hook-serifed-both-sides"
capital-l = "motion-serifed"
capital-n = "motion-serifed"
capital-p = "open-motion-serifed"
capital-r = "curly-open-motion-serifed"
capital-s = "bilateral-inward-serifed"
capital-t = "motion-serifed"
capital-u = "toothless-corner-unilateral-motion-serifed"
capital-v = "curly-motion-serifed"
capital-w = "curly-motion-serifed"
capital-x = "curly-motion-serifed"
capital-y = "curly-motion-serifed"
capital-z = "curly-bottom-serifed-with-crossbar"
a = "single-storey-earless-corner-serifed"
b = "toothless-corner-motion-serifed"
c = "bilateral-inward-serifed"
d = "toothless-corner-serifed"
e = "rounded"
g = "single-storey-flat-hook-serifed"
h = "straight-motion-serifed"
i = "serifed-diagonal-tailed"
j = "diagonal-tailed-serifed"
k = "cursive-top-left-serifed"
l = "serifed-diagonal-tailed"
m = "short-leg-tailed-top-left-serifed"
n = "tailed-motion-serifed"
p = "motion-serifed"
q = "earless-corner-diagonal-tailed"
r = "top-serifed"
s = "bilateral-inward-serifed"
t = "diagonal-tailed-short-neck2"
u = "toothless-corner-motion-serifed"
v = "cursive-serifed"
w = "curly-motion-serifed"
x = "curly-motion-serifed"
y = "curly-turn-motion-serifed"
z = "curly-serifed"
seven = "bend-crossbar-serifed"
 
  [buildPlans.pyrasevid-term.ligations]
  inherits = "dlig"

[buildPlans.pyrasevid-quasi]
family = "pyrasevid quasi"
spacing = "quasi-proportional"
serifs = "sans"
no-cv-ss = false
 
[buildPlans.pyrasevid-quasi.variants.design]
capital-a = "curly-serifless"
capital-b = "standard-unilateral-serifed"
capital-c = "bilateral-inward-serifed"
capital-d = "more-rounded-unilateral-serifed"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothless-corner-serifless-hooked"
capital-h = "top-left-serifed"
capital-i = "serifed"
capital-j = "flat-hook-serifed"
capital-k = "curly-serifless"
capital-l = "serifless"
capital-m = "hanging-motion-serifed"
capital-p = "open"
capital-q = "horizontal-tailed"
capital-r = "curly-open"
capital-s = "unilateral-inward-serifed"
capital-u = "toothless-corner"
capital-v = "curly"
capital-w = "curly"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "curly-serifless"
a = "single-storey-earless-corner-tailed"
b = "toothless-corner"
c = "unilateral-inward-serifed"
d = "toothless-corner-serifless"
e = "flat-crossbar"
f = "serifless"
g = "single-storey-earless-corner-flat-hook"
h = "straight"
i = "serifed-flat-tailed"
j = "flat-hook-serifed"
k = "curly-serifless"
l = "serifed-flat-tailed"
m = "earless-corner-double-arch-short-leg"
n = "earless-corner-straight"
p = "earless-corner"
q = "earless-corner-tailed"
r = "serifless"
s = "unilateral-inward-serifed"
t = "flat-hook-short-neck2"
u = "toothless-corner"
v = "curly"
w = "curly"
x = "curly-serifless"
y = "curly-turn"
z = "curly-serifless"
long-s = "flat-hook"
eszet = "longs-s-lig"
turn-v = "curly"
lower-alpha = "crossing"
lower-delta = "rounded"
capital-gamma = "serifless"
zero = "slashed"
one = "no-base-long-top-serif"
two = "curly-neck"
three = "two-arcs"
four = "semi-open"
five = "vertical-upper-left-bar"
six = "closed-contour"
seven = "bend-crossbar"
eight = "crossing-asymmetric"
nine = "closed-contour"
asterisk = "penta-low"
caret = "low"
paren = "large-contour"
brace = "curly-flat-boundary"
ampersand = "et-toothless-rounded"
at = "short"
dollar = "interrupted-cap"
cent = "bar-interrupted"
percent = "rings-segmented-slash"
lig-ltgteq = "slanted"
question = "corner-flat-hooked"
punctuation-dot = "square"
 
[buildPlans.pyrasevid-quasi.variants.italic]
capital-a = "curly-top-serifed"
capital-b = "standard-bilateral-serifed"
capital-c = "unilateral-inward-serifed"
capital-d = "standard-bilateral-serifed"
capital-e = "top-left-serifed"
capital-f = "top-left-serifed"
capital-g = "toothed-inward-serifed-hooked"
capital-h = "top-left-bottom-right-serifed"
capital-i = "serifed"
capital-j = "flat-hook-serifed-both-sides"
capital-l = "motion-serifed"
capital-n = "motion-serifed"
capital-p = "open-motion-serifed"
capital-r = "curly-open-motion-serifed"
capital-s = "bilateral-inward-serifed"
capital-t = "motion-serifed"
capital-u = "toothless-corner-unilateral-motion-serifed"
capital-v = "curly-motion-serifed"
capital-w = "curly-motion-serifed"
capital-x = "curly-motion-serifed"
capital-y = "curly-motion-serifed"
capital-z = "curly-bottom-serifed-with-crossbar"
a = "single-storey-earless-corner-serifed"
b = "toothless-corner-motion-serifed"
c = "bilateral-inward-serifed"
d = "toothless-corner-serifed"
e = "rounded"
g = "single-storey-flat-hook-serifed"
h = "straight-motion-serifed"
i = "serifed-diagonal-tailed"
j = "diagonal-tailed-serifed"
k = "cursive-top-left-serifed"
l = "serifed-diagonal-tailed"
m = "short-leg-tailed-top-left-serifed"
n = "tailed-motion-serifed"
p = "motion-serifed"
q = "earless-corner-diagonal-tailed"
r = "top-serifed"
s = "bilateral-inward-serifed"
t = "diagonal-tailed-short-neck2"
u = "toothless-corner-motion-serifed"
v = "cursive-serifed"
w = "curly-motion-serifed"
x = "curly-motion-serifed"
y = "curly-turn-motion-serifed"
z = "curly-serifed"
seven = "bend-crossbar-serifed"
 
  [buildPlans.pyrasevid-quasi.ligations]
  inherits = "dlig"
