#!/bin/sh
export HISTFILE="$ZDOTDIR"/zsh-history
export HISTSIZE=1000000
export SAVEHIST=1000000
# export PATH="$HOME/.local/bin":$PATH
# export MANPAGER="nvim +Man!"
export MANPAGER="sh -c 'col -bx | bat --theme Nord -l man -p'"
# export MANPAGER="nvimpager"
export PAGER="nvimpager"
export GOPATH="$HOME/.local/go"
export PATH="$PATH:$GOPATH"

man() {
	width=$(tput cols)
	[ "$width" -gt "$MANWIDTH" ] && width=$MANWIDTH
	env MANWIDTH="$width" \
	man "$@"
}

export EDITOR="code"
export TERMINAL="alacritty"
export BROWSER="firefox"
