#!/bin/sh

echo "==> Installing paru..."
sudo pacman -S --needed base-devel --noconfirm
git clone https://aur.archlinux.org/paru.git paru/
cd paru/ && makepkg -si

paru -S $(cat pkgs | awk '{print $1}')
