#! /bin/sh
##  /\\\
##  \/\\\
##   \/\\\                       /\\\\\\\\\
##    \/\\\         /\\\\\\\\\\  /\\\/////\\\  /\\    /\\   /\\    /\\\\\  /\\\\\    /\\/\\\\\\\      /\\\\\\\\
##     \/\\\\\\\\\  \/\\\//////  \/\\\\\\\\\\  \/\\\  /\\\\ /\\\  /\\\///\\\\\///\\\ \/\\\/////\\\   /\\\//////
##      \/\\\////\\\ \/\\\\\\\\\\ \/\\\//////   \//\\\/\\\\\/\\\  \/\\\ \//\\\  \/\\\ \/\\\   \///   /\\\
##	     \/\\\  \/\\\ \////////\\\ \/\\\          \//\\\\\/\\\\\   \/\\\  \/\\\  \/\\\ \/\\\         \//\\\
##        \/\\\\\\\\\   /\\\\\\\\\\ \/\\\           \//\\\\//\\\    \/\\\  \/\\\  \/\\\ \/\\\          \///\\\\\\\\
##         \/////////   \//////////  \///             \///  \///     \///   \///   \///  \///             \////////
##
### AUTOSTART ###
nitrogen --restore &
pgrep -x sxhkd > /dev/null || sxhkd &
picom --log-file ~/docs/logs/picom.log --experimental-backends &
# figure out what -> is # /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/bin/wired &
flameshot &
clipmenud &
~/ne/dld/dld &

## CURSOR ##
xsetroot -cursor_name left_ptr
~/bin/fixmouse &

## COLORS
xrdb ~/.Xresources
getcolors() {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors

## MONITORS

# MAIN & SECOND XRANDR CONFIG #
xrandr --output DP-2 --primary --mode 2560x1440 --rate 165 --output DP-4 --mode 1920x1080 --rate 120 --left-of DP-2 &

# WORKSPACES #
start_from=1
monitors_connected=$(bspc query -M | wc -l)
per_monitor=$(( 10 / monitors_connected ))
for monitor in $(bspc query -M | tac); do
    bspc monitor "$monitor" -d $(seq $start_from $(( start_from + per_monitor - 1)))
    start_from=$((start_from + per_monitor))
done

# POLYBAR #
~/.config/polybar/launch.sh &

## COLORS ##
bspc config normal_border_color   "$BACKGROUND"
bspc config focused_border_color  "$MAGENTA"
bspc config active_border_color   "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

## RULES ##
# example: bspc rule -a Firefox state=floating follow=on desktop='^5'
bspc rule -a Nitrogen           state=floating
bspc rule -a vlc                state=floating desktop='5' follow=on
bspc rule -a wine               state=floating desktop='5'
bspc rule -a "golden apple.exe" state=floating desktop='5'
bspc rule -a lunarclient        state=floating desktop='5'
bspc rule -a Steam              state=floating desktop='5' follow=on
bspc rule -a Code               desktop='3' focus=on
bspc rule -a Alacritty          desktop='1' focus=on
bspc rule -a firefox            desktop='2' focus=on
bspc rule -a KeyOverlay         state=floating
bspc rule -a spotifytui         follow=on desktop='6'

## BORDERS ##
bspc config border_width 3
bspc config window_gap   16

## OTHER SHIT ##
bspc config split_ratio  0.52

## POINTER ACTIONS ##
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config focus_follows_pointer true
bspc config borderless_monocle    true
bspc config gapless_monocle       true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
